### ISSUE TITLE
Modify plugin to allow using large query scope returning 1 value(count, sum, percentile....)

### ISSUE THREAD

**Issue by pmouawad** [jenkinsci/influxdb-query-plugin#10]
Currently the plugin runs a query and compares the number of rows returned to succeed or fail.

I think it would be more generic and powerful to do the following:

- User enters a query that is supposed to return a numerical value (count or percentile or whatever)
- User also inputs a threshold

Plugins runs the query, compares it to threshold and fails the build if value above.

This would do what the plugin currently does.
But this would be more powerful as it would allow user to make queries on some values, for example in Load Testing he would run a percentile on a set of values and decides what to do

If you're OK, I'll modify the plugin.
Thanks

**Comment by JoeOffenberg** [comment]
This is great.  Thanks for taking this on.  I will add you as a contributor.

**Comment by pmouawad** [comment]
Hello @JoeOffenberg ,
Thanks.
Does it mean I'll be able to commit on repository or it's something else ?

Could you accept the current PR so that I start work from a clean situation ?
Thanks

**Comment by pmouawad** [comment]
Hi @JoeOffenberg,
Are you ok for commit ?

Thanks
