### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by pmouawad** [jenkinsci/influxdb-query-plugin#13]
Milestone 1.0

**Comment by pmouawad** [comment]
@JoeOffenberg , 

- Would you be ok to release 1.0 instead of 0.46 ?
- How do we update this page https://jenkins.io/doc/pipeline/steps/influxdb-query/

**Comment by JoeOffenberg** [comment]
That page is updated from
https://wiki.jenkins.io/display/JENKINS/InfluxDB+Plugin you should be able
to make changes with your jenkins.io account.  If you are done with your
updates for the time being, I will release 1.0

**Comment by pmouawad** [comment]
Hi @JoeOffenberg ,
I updated few minutes ago:

- https://wiki.jenkins.io/display/JENKINS/InfluxDB+Query+Plugin

But I don't see this one updated:

- https://jenkins.io/doc/pipeline/steps/influxdb-query/

Thanks

**Comment by pmouawad** [comment]
Yes I am done with 1.0 version, as per Milestone content.

**Comment by pmouawad** [comment]
@JoeOffenberg, the steps doc will be updated over the weekend as per:

- https://stackoverflow.com/questions/53400376/how-is-jenkins-pipeline-steps-documentation-of-a-plugin-updated

**Comment by pmouawad** [comment]
Done today by @JoeOffenberg
